Improve arolla.abc.Operator.__call__ error reporting
The frame corresponding to the method __call__() is now hidden when an error occurs while doing the argument binding, and there are no further frames in the traceback.

```
from arolla import arolla

print(arolla.M.math.add(1))

# Traceback (most recent call last):
#   File "test.py", line 3, in <module>
#     print(arolla.M.math.add(1))
#           ^^^^^^^^^^^^^^^^^^^^
# TypeError: missing 1 required positional argument: 'y'
```

PiperOrigin-RevId: 865422601
Change-Id: Id36dde6340a6ca88aeef0abda471208b6bb06043