A patch for arolla::BoundInputLoader<Input>::FnType for compatibility with g++ 12
`$ bazel build :typed_refs_input_loader_test`

```
INFO: Analyzed target //arolla/io:typed_refs_input_loader_test (0 packages loaded, 0 targets configured).
ERROR: /build/arolla/arolla/io/BUILD:19:11: Compiling arolla/io/typed_refs_input_loader.cc failed: (Exit 1): gcc failed: error executing CppCompile command (from target //arolla/io:io) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++17' -MD -MF ... (remaining 50 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from /usr/include/c++/11/bits/move.h:57,
                 from /usr/include/c++/11/bits/stl_pair.h:59,
                 from /usr/include/c++/11/bits/stl_algobase.h:64,
                 from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from ./arolla/io/typed_refs_input_loader.h:18,
                 from arolla/io/typed_refs_input_loader.cc:15:
/usr/include/c++/11/type_traits: In instantiation of 'struct std::is_constructible<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >, const arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >&>':
external/abseil-cpp+/absl/functional/internal/any_invocable.h:704:7:   required by substitution of 'template<class Sig, class F, class> using CanConvert = absl::lts_20240722::internal_any_invocable::TrueAlias<typename std::enable_if<(! absl::lts_20240722::internal_any_invocable::IsInPlaceType<typename std::remove_cv<typename std::remove_reference<_Arg>::type>::type>::value), void>::type, typename std::enable_if<typename absl::lts_20240722::internal_any_invocable::Impl<Sig>::CallIsValid<F>::value, void>::type, typename std::enable_if<typename absl::lts_20240722::internal_any_invocable::Impl<Sig>::CallIsNoexceptIfSigIsNoexcept<F>::value, void>::type, typename std::enable_if<std::is_constructible<typename std::decay<_Tp2>::type, F>::value, void>::type> [with Sig = absl::lts_20240722::Status(const absl::lts_20240722::Span<const arolla::TypedRef>&, arolla::FramePtr, arolla::RawBufferFactory*) const; F = const arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >&; <template-parameter-1-3> = void]'
external/abseil-cpp+/absl/functional/any_invocable.h:191:22:   required by substitution of 'template<class F, class> absl::lts_20240722::AnyInvocable<absl::lts_20240722::Status(const absl::lts_20240722::Span<const arolla::TypedRef>&, arolla::FramePtr, arolla::RawBufferFactory*) const>::AnyInvocable(F&&) [with F = const arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >&; <template-parameter-1-2> = <missing>]'
/usr/include/c++/11/type_traits:946:30:   required from 'struct std::__is_constructible_impl<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >, const arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >&>'
/usr/include/c++/11/type_traits:977:12:   required from 'struct std::__is_copy_constructible_impl<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >, true>'
/usr/include/c++/11/type_traits:984:12:   required from 'struct std::is_copy_constructible<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> > >'
external/abseil-cpp+/absl/status/statusor.h:192:7:   required from 'class absl::lts_20240722::StatusOr<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> > >'
arolla/io/typed_refs_input_loader.cc:52:22:   required from here
/usr/include/c++/11/type_traits:952:12: error: invalid use of incomplete type 'struct std::__is_constructible_impl<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >, const arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >&>'
  952 |     struct is_constructible
      |            ^~~~~~~~~~~~~~~~
/usr/include/c++/11/type_traits:945:12: note: declaration of 'struct std::__is_constructible_impl<arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >, const arolla::BoundInputLoader<absl::lts_20240722::Span<const arolla::TypedRef> >&>'
  945 |     struct __is_constructible_impl
      |            ^~~~~~~~~~~~~~~~~~~~~~~
Target //arolla/io:typed_refs_input_loader_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.469s, Critical Path: 2.27s
INFO: 13 processes: 13 internal.
ERROR: Build did NOT complete successfully
```
PiperOrigin-RevId: 746031532
Change-Id: I991d0de7d37c8b8640af83f1c1229be52f2d29b5