`JaggedShapeEquivalentTo` matcher
We may consider turning it into some generic `IsEquivalentTo` matcher later.

Example:
```
ERROR: No public description
Value of: shape1
Expected: is equivalent to JaggedShape(2, [1, 3])
  Actual: 0x301e7fe07aa0, pointing to JaggedShape(2, [1, 2]) which is not equivalent
Stack trace:
0x7f5deecda7cd: arolla::(anonymous namespace)::QTypeTest_JaggedShapeEquivalentTo_Test::TestBody() @ ??:??
0x7f5d9afc0c92: testing::Test::Run() @ ??:??
0x7f5d9afc1bb9: testing::TestInfo::Run() @ ??:??
... Google Test internal frames ...
```
PiperOrigin-RevId: 625981957
Change-Id: I4bc1e1de6fdc3b457b789d3c02ee0e9fa0d9b136